vuejs-translations/docs-pt

src/api/application.md
Translate docs/api/application.md file to Portuguese
Solves first item of issue #3
=> docs(pt): translate `docs/api/application.md`

src/api/general.md
=> docs(pt): translate `api/general.md`

src/api/composition-api-setup.md
=> docs(pt): translate `api/composition-api-setup.md`

src/api/composition-api-dependency-injection.md
=> docs(pt): translate `api/composition-api-dependency-injection.md` #10

src/api/options-rendering.md
=> docs(pt): translate `api/options-rendering.md` #19

src/api/index.md
=> docs(pt): translate `api/index.md` #15

src/api/built-in-special-attributes.md
=> docs(pt): translate `api/built-in-special-attributes.md`

src/api/custom-renderer.md
=> docs(pt): translate `api/custom-renderer.md`

src/api/options-state.md
=> docs(pt): translate `api/options-state.md`

src/api/utility-types.md
=> docs(pt): translate api/utility-types.md

src/api/built-in-special-elements.md
=> docs(pt): translate `api/build-in-special-elements.md`

src/api/sfc-spec.md
=> docs(pt): translate `api/sfc-spec.md`

src/api/ssr.md
=> docs(pt): translate api/ssr.md

src/api/utility-types.md
=> docs(pt): update `api/utility-types.md`

src/api/options-composition.md
=> docs(pt): translate `api/options-composition.md`

src/api/reactivity-core.md
=> docs(pt): translate `api/reactivity-core.md`

src/api/built-in-directives.md
=> docs(pt): translate `api/built-in-directives.md`

src/api/reactivity-utilities.md
=> docs(pt): translate `api/reactivity-utilities.md`

src/api/component-instance.md
=> docs(pt): translate `api/component-instance.md`

src/api/composition-api-lifecycle.md
=> docs(pt): translate `api/composition-api-lifecycle.md` #11

src/api/sfc-css-features.md
=> docs(pt): translate `api/sfc-css-features.md`

src/api/sfc-script-setup.md
=> docs(pt): translate `api/sfc-script-setup.md`

src/api/reactivity-advanced.md
=> docs(pt): translate `api/reactivity-advanced.md`

src/style-guide/rules-use-with-caution.md
=> docs(pt): translate style-guide/rules-use-with-caution.md #48

src/style-guide/rules-recommended.md
=> docs(pt): translate style-guide/rules-recommended.md #46

src/guide/essentials/template-syntax.md
The URL to globals allowed list was wrong
Update the url link to globals allow list
=> fix(docs): update globals allow list url

src/style-guide/rules-essential.md
=> docs(pt): translate `style-guide/rules-essential.md` #45

src/style-guide/rules-strongly-recommended.md
=> docs(pt): translate `style-guide/rules-strongly-recommended.md` #47

src/guide/scaling-up/state-management.md
=> review and suggestions guide/scaling-up/state-management #110

src/guide/scaling-up/state-management.md, src/guide/scaling-up/tooling.md
=> #112 review and suggestions guide/scaling-up/tooling #112

src/guide/best-practices/security.md
Solves  #141
Note: I found the word 'sandbox' literally translated as sandbox, I did some research and noticed that its context within programming could be 'área restrita'
=> docs(pt): review security #141 

src/guide/reusability/composables.md
- Replace 're-ler' with 'reler' in initial tip section
=> Fix typo in composables.md

src/guide/components/registration.md
Impedi é passado de impede.
Impedi é passado de impede.
mudança de impedi para impede
=> docs: update `guide/components/registration.md`

src/guide/introduction.md
=> Fix introduction.md

README.md
=> chore: update `readme.md` file to provide more clear language
